### ISSUE TITLE
Set the front of the covarience to `-1` to express `UNUSED`

### ISSUE THREAD

**Issue by m12watanabe1a** [HarvestX/MGS1600GY-ROS2#43]
Now the bare topic is like this.
And check the lines with `# Need to be -1`

```
header:
  stamp:
    sec: 1671613352
    nanosec: 746524577
  frame_id: mgs1600gy_link
orientation:
  x: -0.25434098888304396
  y: 0.4801277513756575
  z: 0.036559869881750084
  w: 0.8387200842040088
orientation_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
angular_velocity:
  x: 0.0
  y: 0.0
  z: 0.0
angular_velocity_covariance:
- 0.0 # Need to be -1
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
linear_acceleration:
  x: 0.0
  y: 0.0
  z: 0.0
linear_acceleration_covariance:
- 0.0 # Need to be -1
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
```

## Requirements
- MGS1600gy

## Start program
```bash
ros2 launch mgs1600gy_bringup mgs1600gy.launch.py dev:=/dev/ttyACM0
```
